header:
  license:
    spdx-id: Apache-2.0
    content: |
      SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Juno contributors
      SPDX-License-Identifier: Apache-2.0

  paths: # `paths` are the path list that will be checked (and fixed) by license-eye, default is ['**'].
    - "**"

  paths-ignore:
    - ".github/**"
    - "apis/**"
    - "assets/**"
    - ".npmignore"
    - "**/*.npmignore"
    - "**/*.npmrc"
    - ".npmrc"
    - "CODEOWNERS"
    - "bin/**"
    - "ci/**"
    - "config/**"
    - "docker/**"
    - "docs/**"
    - "e2e/**"
    - "**/*.md"
    - "LICENSE"
    - "**/LICENSE"
    - "**/*.gitignore"
    - "**/*.dockerignore"
    - "**/*.helmignore"
    - "**/*.tpl"
    - "**/go.mod"
    - "**/go.sum"
    - "**/*.lock"
    - "**/*.json"
    - "**/.gitkeep"
    - "**/*.txt"
    - "*Dockerfile*"
    - "Makefile"
    - "**/*.map"

  comment: on-failure

  # license-location-threshold specifies the index threshold where the license header can be located,
  # after all, a "header" cannot be TOO far from the file start.
  license-location-threshold: 80

  language:
    JSX:
      extensions:
        - ".jsx"
      comment_style_id: SlashAsterisk
    MDX:
      extensions:
        - ".mdx"
      comment_style_id: Custom
      after: '(?ms)^<\?.+?\?>$'
      start: "/-"
      middle: "  ~"
      end: "-/"
