enableMirror: false
# Because the hoisting heuristics aren't standardized and predictable,
# PnP operating under strict mode will prevent packages to require
# dependencies that they don't explicitly list (even if one of their
# other dependencies happens to depend on it). This may cause issues
# with some packages.
#
# To address this problem, Yarn ships with a "loose" mode
# pnpMode: loose

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-2.4.1.cjs
packageExtensions:
  # needed by juno-ui-components
  "@fullhuman/postcss-purgecss@*":
    dependencies:
      "postcss": "*"
  "sass-loader@*":
    dependencies:
      "sass": "*"
