yarnPath: ".yarn/releases/yarn-berry.cjs"
enableMirror: false

# nmHoistingLimits: workspaces
# nodeLinker: node-modules

packageExtensions:
  "styled-components@*":
    dependencies:
      "babel-plugin-macros": "*"
