# do not activate!!!
# nodeLinker: "node-modules"
enableMirror: false

packageExtensions:
  "@fullhuman/postcss-purgecss@*":
    dependencies:
      postcss: "*"
  "@storybook/core-server@*":
    dependencies:
      "@storybook/manager-webpack5": "*"
  postcss-loader@*:
    dependencies:
      autoprefixer: "*"
      tailwindcss: "*"
  sass-loader@*:
    dependencies:
      sass: "*"
  sequelize-test-helpers@*:
    dependencies:
      chai: "*"
      sinon: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.1.0.cjs
