overrides:
  esbuild@<=0.24.2: '>=0.25.0'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  minimatch@>=5.0.0 <5.1.7: '>=5.1.7'
  minimatch@>=9.0.0 <9.0.6: '>=9.0.6'
  minimatch@>=5.0.0 <5.1.8: '>=5.1.8'
  minimatch@>=9.0.0 <9.0.7: '>=9.0.7'
  brace-expansion@>=2.0.0 <2.0.3: '>=2.0.3'
  picomatch@<2.3.2: '>=2.3.2'
  yaml@>=2.0.0 <2.8.3: '>=2.8.3'
