kind: Service
apiVersion: v1

metadata:
  namespace: juno
  name: assets-server
  annotations:
    {{- if and $.Values.global.linkerd_enabled $.Values.global.linkerd_requested }}
    linkerd.io/inject: enabled
    {{- end }}

spec:
  selector:
    app: assets-server
  ports:
    - name: assets-server
      port: 8888
      targetPort: 80
      protocol: TCP
