kind: Service
apiVersion: v1

metadata:
  namespace: greenhouse
  name: ui-dashboard

spec:
  selector:
    app: ui-dashboard
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: web
