kind: Service
apiVersion: v1

metadata:
  namespace: juno
  name: juno-cdn

spec:
  selector:
    app: juno-cdn
  ports:
    - name: juno-cdn
      port: 8888
      targetPort: 80
      protocol: TCP
