kind: Service
apiVersion: v1

metadata:
  namespace: juno
  name: hosting

spec:
  selector:
    app: hosting
  ports:
    - name: dashboard
      port: 80
      protocol: TCP
      targetPort: web
    - name: exampleapp
      port: 81
      protocol: TCP
      targetPort: web
