kind: Service
apiVersion: v1

metadata:
  namespace: juno
  name: hosting
  annotations:
    {{- if and $.Values.global.linkerd_enabled $.Values.global.linkerd_requested }}
    linkerd.io/inject: enabled
    {{- end }}

spec:
  selector:
    app: hosting
  ports:
    - name: dashboard
      port: 80
      protocol: TCP
      targetPort: dashboard
    - name: exampleapp
      port: 81
      protocol: TCP
      targetPort: exampleapp
