apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    dns-manager: "true"
    dns-manager/zone-name: "{{ .Values.global.region }}.{{ .Values.global.tld }}"
    kubernetes.io/tls-acme: "true"
    # disable the idle http timeout check
    # https://operations.global.cloud.sap/docs/support/playbook/kubernetes/idle_http_keep_alive_timeout.html
    cloud.sap/no-http-keep-alive-monitor: "true"
    ingress.kubernetes.io/cors-allow-origin: '*'
    ingress.kubernetes.io/enable-cors: "true"

  name: ingress-###NAME###
  namespace: juno
spec:
  rules:
    - host: "###NAME###.juno.{{ .Values.global.region }}.{{ .Values.global.tld }}"
      http:
        paths:
          - path: /
            pathType: Prefix 
            backend:
              service: 
                name: hosting-###NAME###
                port: 
                  number: 80           
                    
{{- if eq .Values.global.region "eu-nl-1" }}
    - host: "###NAME###.juno.global.{{ .Values.global.tld }}"
      http:
        paths:
          - path: /
            pathType: Prefix 
            backend:
              service: 
                name: hosting-###NAME###
                port: 
                  number: 80               
{{- end }} 

  tls:
    - hosts: 
        - "###NAME###.juno.global.{{ .Values.global.tld }}"
{{- if eq .Values.global.region "eu-nl-1" }}    
        - "###NAME###.juno.global.{{ .Values.global.tld }}"  
{{- end }}        
      secretName: "tls-juno-###NAME###"