kind: Deployment
apiVersion: apps/v1

metadata:
  name: hosting
  namespace: juno

spec:
  selector:
    matchLabels:
      app: hosting
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        app: hosting
    spec:
      # The preStop hook below sleeps 30 seconds, extend the gracePeriod accordingly
      terminationGracePeriodSeconds: 60
      containers:
        
      {{- range $i, $app := .Values.apps  }}
        - name: hosting-{{ $app.name }}
          image: "{{ .Values.global.registry }}/juno-v2-hosting:{{ .Values.image_tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ add 3000 $i }}

          livenessProbe:
            httpGet:
              path: /
              port: {{ add 3000 $i }}
            timeoutSeconds: 10
            periodSeconds: 60
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /
              port: {{ add 3000 $i }}
            timeoutSeconds: 5
            periodSeconds: 5
          resources:
            limits:
              cpu: "1000m"
              memory: "256Mi"
            requests:
              cpu: "1000m"
              memory: "256Mi"
          lifecycle:
            preStop:
              exec:
                #Give the ingress some time to reload its config
                command: ["/bin/sh", "-c", "sleep 30"]
      {{- end }}