kind: Ingress
apiVersion: networking.k8s.io/v1

metadata:
  name: ingress-assets-server-noop
  namespace: juno
  annotations:
    # ingress controller only creates certs as secret
    kubernetes.io/ingress.class: "noop.cert-manager"
    # enable cert-manager
    kubernetes.io/tls-acme: "true"
spec:
  tls:
     - secretName: tls-asset-manager
       hosts: 
         - {{ .Values.endpoint_host }}.{{ .Values.global.region }}.{{ .Values.global.tld }}
  # the following is mandatory in an ingress resource, but will be ignored by the vice-president
  rules:
    - host: {{ .Values.endpoint_host }}.{{ .Values.global.region }}.{{ .Values.global.tld }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: assets-server
              port: 
                number: 443