apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: juno
data:
  nginx.conf: |
    server { 
        listen       443 ssl default_server; 
        server_name  {{ .Values.endpoint_host }}.{{ .Values.global.region }}.{{ .Values.global.tld }}; 
        ssl_certificate     /tls-secret/tls.crt;
        ssl_certificate_key /tls-secret/tls.key;

        add_header 'Access-Control-Allow-Origin' '*';

        location / {
            root   /usr/share/nginx/html; 
            index  index.html index.htm; 
        } 

        location ~* (importmap|manifest).*\.json$ { 
            root  /usr/share/nginx/html; 
            sub_filter '%BASE_URL%' "https://$host"; 
            sub_filter_types *; 
            sub_filter_once off; 
            add_header Cache-Control "no-store, no-cache"; 
        } 

        location ~* .*widget-loader@latest.*\.js$ { 
            root /usr/share/nginx/html; 
            add_header Cache-Control "no-store, no-cache"; 
        }

        #error_page  404              /404.html; 
        # redirect server error pages to the static page /50x.html 
        error_page   500 502 503 504  /50x.html; 

        location = /50x.html { 
            root   /usr/share/nginx/html; 
        } 
    } 