kind: Service
apiVersion: v1

metadata:
  namespace: juno
  name: juno-assets-server

spec:
  selector:
    app: juno-assets-server
  ports:
    - name: juno-assets-server
      port: 8888
      targetPort: 80
      protocol: TCP
