apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    dns-manager: "true"
    dns-manager/zone-name: "{{ .Values.global.region }}.{{ .Values.global.tld }}"
    kubernetes.io/tls-acme: "true"
    # disable the idle http timeout check
    # https://operations.global.cloud.sap/docs/support/playbook/kubernetes/idle_http_keep_alive_timeout.html
    cloud.sap/no-http-keep-alive-monitor: "true"
  name: ingress-ui-storybook
  namespace: juno
spec:
  rules:
    - host: "ui.juno.{{ .Values.global.region }}.{{ .Values.global.tld }}"
      http:
        paths:
          - path: /
            pathType: Prefix                 
            backend:
              service: 
                name: ui-storybook
                port: 
                  number: 3000                  
                    
{{- if eq .Values.global.region "eu-nl-1" }}
    - host: "ui.juno.global.{{ .Values.global.tld }}"
      http:
        paths:
          - path: /
            pathType: Prefix                 
            backend:
              service: 
                name: ui-storybook
                port: 
                  number: 3000                  

{{- end }} 

  tls:
    - hosts: 
        - "ui.juno.{{ .Values.global.region }}.{{ .Values.global.tld }}"
{{- if eq .Values.global.region "eu-nl-1" }}    
        - "ui.juno.global.{{ .Values.global.tld }}"  
{{- end }}        
      secretName: "tls-juno-ui-storybook"