kind: Service
apiVersion: v1

metadata:
  namespace: juno
  name: ui-storybook
  annotations:
    {{- if and $.Values.global.linkerd_enabled $.Values.global.linkerd_requested }}
    linkerd.io/inject: enabled
    {{- end }}

spec:
  selector:
    app: ui-storybook
  ports:
    - name: ui-storybook
      port: 3000
      protocol: TCP
