# prettier-ignore

kind: Deployment
apiVersion: apps/v1

metadata:
  name: assets-server
  namespace: juno

spec:
  selector:
    matchLabels:
      app: assets-server
  revisionHistoryLimit: 3
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        app: assets-server
      annotations:
        # we use timestamp to pull latest image without downtime
        # https://github.com/helm/helm/issues/5218
        # timestamp: "{{ now | date "20060102150405" }}"        
    spec:
      # The preStop hook below sleeps 30 seconds, extend the gracePeriod accordingly
      terminationGracePeriodSeconds: 60
      containers:
        - name: server
          image: "{{ .Values.global.registry }}/juno-v3-assets-server:{{.Values.image.tag}}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: https
              containerPort: 443
          livenessProbe:
            httpGet:
              scheme: "HTTPS"
              path: /manifest.json
              port: 443
            timeoutSeconds: 10
            periodSeconds: 60
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              scheme: "HTTPS"
              path: /manifest.json
              port: 443
            timeoutSeconds: 5
            periodSeconds: 
          resources:
            limits:
              cpu: "1000m"
              memory: "256Mi"
            requests:
              cpu: "1000m"
              memory: "256Mi"
          lifecycle:
            preStop:
              exec:
                #Give the ingress some time to reload its config
                command: ["/bin/sh", "-c", "sleep 30"]
          volumeMounts:
            - mountPath: /etc/ssl/juno
              name: tls-secret          
      volumes:
        - name: tls-secret
          secret:
            secretName: tls-assets-juno
