apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
    # disable the idle http timeout check
    # https://operations.global.cloud.sap/docs/support/playbook/kubernetes/idle_http_keep_alive_timeout.html
    cloud.sap/no-http-keep-alive-monitor: "true"
    ingress.kubernetes.io/cors-allow-origin: "*"
    ingress.kubernetes.io/enable-cors: "true"

  name: ui-dashboard
  namespace: greenhouse
spec:
  rules:
    - host: "greenhouse-qa.{{ .Values.global.region }}.{{ .Values.global.tld }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ui-dashboard
                port:
                  number: 80

  tls:
    - hosts:
        - "greenhouse-qa.{{ .Values.global.region }}.{{ .Values.global.tld }}"
      secretName: "tls-ui-dashboard"
