apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    dns-manager: "true"
    dns-manager/zone-name: "{{ .Values.global.region }}.{{ .Values.global.tld }}"
    kubernetes.io/tls-acme: "true"
    # disable the idle http timeout check
    # https://operations.global.cloud.sap/docs/support/playbook/kubernetes/idle_http_keep_alive_timeout.html
    cloud.sap/no-http-keep-alive-monitor: "true"
    ingress.kubernetes.io/cors-allow-origin: '*'
    ingress.kubernetes.io/enable-cors: "true"

  name: ingress-exampleapp
  namespace: juno
spec:
  rules:
    - host: "exampleapp.juno.{{ .Values.global.region }}.{{ .Values.global.tld }}"
      http:
        paths:
          - path: /
            pathType: Prefix 
            backend:
              service: 
                name: hosting-exampleapp
                port: 
                  number: 80           
                    
{{- if eq .Values.global.region "eu-nl-1" }}
    - host: "exampleapp.juno.global.{{ .Values.global.tld }}"
      http:
        paths:
          - path: /
            pathType: Prefix 
            backend:
              service: 
                name: hosting-exampleapp
                port: 
                  number: 80               
{{- end }} 