kind: Service
apiVersion: v1

metadata:
  namespace: juno
  name: hosting-exampleapp

spec:
  selector:
    app: hosting-exampleapp
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: web
