apiVersion: v1
description: A Helm chart for installing the Juno assets server
name: assets_server
version: 0.1.0
dependencies:
  - name: owner-info
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.2.0
