apiVersion: v2
description: A Helm chart for installing the assets server
name: assets-server
version: 1.0.0
dependencies:
  - name: owner-info
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.2.0
