FROM keppel.eu-de-1.cloud.sap/ccloud-dockerhub-mirror/library/nginx:alpine

LABEL source_repository="https://github.com/sapcc/juno/ci/Dockerfile.cdn"

RUN apk --no-cache add git ca-certificates make

RUN mkdir -p /usr/share/nginx/html/cdn

RUN mkdir -p /tmp/build
COPY . /tmp/build/

RUN cp -rf /tmp/build/* /usr/share/nginx/html/cdn/ && rm -rf /tmp/build
