FROM nginx:alpine

LABEL source_repository="https://github.com/sapcc/juno/tree/main/config/error-pages"

# Remove default NGINX Config
# Take care of Nginx logging


RUN rm /etc/nginx/conf.d/default.conf && \
    ln -sf /dev/stdout /var/log/nginx/access.log && \
    ln -sf /dev/stderr /var/log/nginx/error.log

# NGINX Config

RUN echo -e '\n\
server {                         \n\
    root /var/www/html;          \n\
    index 404.html;              \n\
                                 \n\        
    location / {                 \n\
                                 \n\        
    }                            \n\
                                 \n\
    location /healthz {          \n\
        access_log off;          \n\
        return 200 "healthy\\n"; \n\
    }                            \n\
                                 \n\
    location /metrics {          \n\
        # This creates a readable and somewhat useful response for Prometheus\n\
        stub_status on;          \n\
    }                            \n\
                                 \n\
    error_page 404 /404.html;    \n\
    location = /404.html {       \n\
        internal;                \n\
    }                            \n\
}' >> /etc/nginx/conf.d/default.conf

# Resources 

COPY config/error-pages/50x.html /var/www/html/404.html

CMD ["nginx", "-g", "daemon off;"]