FROM keppel.eu-de-1.cloud.sap/ccloud-dockerhub-mirror/library/node:20-alpine
WORKDIR /app

RUN \
  cd libs/juno-ui-components && \
  npm --workspace juno-ui-components install 1>/dev/null && \
  npm --workspace juno-ui-components run build-storybook 1>/dev/null 

LABEL source_repository="https://github.com/cloudoperators/juno/juno-ui-components"

RUN apk --no-cache add ca-certificates && npm install -g http-server

RUN ls -la

# run app
CMD http-server --port 3000 .