apiVersion: v2
description: A Helm chart for hosting an asset
name: hosting
version: 0.1.0
dependencies:
  - name: owner-info
    repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
    version: '>= 0.0.0'
