owner-info:
  helm-chart-url: https://github.com/sapcc/juno/tree/main/ci/helm-charts/hosting
  support-group: containers
  service: juno-hosting
  maintainers:
    - Esther Schmitz
    - Andreas Pfau
    - Hans-Georg Winkler
    - Arturo Reuschenbach Puncernau
    - Hoda Noori

global:
  # No Linkerd annotations will be rendered unless this flag is set to true. This allows you to control when to add your service to the mesh.
  linkerd_requested: true
