# prettier-ignore
kind: Deployment
apiVersion: apps/v1

metadata:
  name: juno-mercury
  namespace: juno

spec:
  selector:
    matchLabels:
      app: juno-mercury
  revisionHistoryLimit: 3
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        app: juno-mercury
    spec:
      # The preStop hook below sleeps 30 seconds, extend the gracePeriod accordingly
      terminationGracePeriodSeconds: 60
      containers:
        - name: mercury
          image: "{{ .Values.global.registry }}/juno-mercury:{{.Values.mercury_tag}}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5000
          env:
            - name: DB_USER
              value: {{ .Values.postgresql.user }}
            - name: DB_PASSWORD
              valueFrom:{ secretKeyRef:    { name: {{ template "postgresql.fullname" . }}, key: postgres-password } }
            - name: DB_NAME
              value: {{ .Values.postgresql.database}}


          livenessProbe:
            httpGet:
              path: /
              port: 5000
            timeoutSeconds: 10
            periodSeconds: 60
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            timeoutSeconds: 5
            periodSeconds: 5
          lifecycle:
            preStop:
              exec:
                #Give the ingress some time to reload its config
                command: ["/bin/sh", "-c", "sleep 30"]
