name: Check & Fix License Header

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-license-eye:
    name: Build LicenseEye
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check License Header
        uses: apache/skywalking-eyes/header@v0.5.0
        with:
          config: .github/licenserc.yaml
          mode: fix

      - name: Set Git Config
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "License Bot"

      - name: Stage Changes
        run: git add .

      - name: Commit Changes
        run: git commit -m "Automatic application of license header"

      - name: Push Changes
        run: git push origin HEAD:${{ github.head_ref }}
