name: Check & Fix License Header
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-license-eye:
    name: Build LicenseEye
    runs-on: [ubuntu-latest]
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check License Header
        uses: apache/skywalking-eyes/header@v0.5.0
        with:
          config: .github/licenserc.yaml
          mode: fix

      - name: Apply Changes
        run: |
          git add .
          git config --local user.email "license_bot@github.com"
          git config --local user.name "License Bot"
          git commit -m "Automatic application of license header"
          git checkout ${{ github.head_ref }}

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
