name: Juno (build & deploy all apps)

on:
  push:
    branches:
      - gh-matrix

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # On release creation
  # release:
  #   types: [created]

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "tests&deployments"
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

# echo "paths=$(ls -d ./apps/*/ | sed 's/^\.\///' | sed 's/$/**/' | jq --raw-input --slurp --compact-output 'split("\n")[:-1]')" >> ${GITHUB_OUTPUT}
# echo "paths=$(ls -d ./apps/*/ | sed 's/^\.\///' | sed 's/$/**/' | sed 's|[^/]*/|"&"|g' | jq --raw-input --slurp --compact-output 'split("\n")[:-1]')" >> ${GITHUB_OUTPUT}
jobs:
  collect_info:
    runs-on: [ubuntu-latest]
    outputs:
      apps: ${{ steps.collect-apps.outputs.apps }}
      paths: ${{ steps.collect-apps.outputs.paths }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Collect apps
        id: collect-apps
        run: |
          echo "apps=$(ls -d ./apps/*/ | jq --raw-input --slurp --compact-output 'split("\n")[:-1]')" >> ${GITHUB_OUTPUT}          
          echo "paths=$(ls -d ./apps/*/ | sed 's/^\.\///' | sed 's/$/**/' | sed 's/^\(.*\)$/\"\1\"/' | jq --raw-input --slurp --compact-output 'split("\n")[:-1]')" >> ${GITHUB_OUTPUT}
      - name: Show outputs
        run: |
          echo "===================="
          echo ${{ steps.collect-apps.outputs.apps }}
          echo "===================="
          echo ${{ steps.collect-apps.outputs.paths }}
          echo "===================="
  changes:
    needs: collect_info
    runs-on: [ubuntu-latest]
    outputs:
      apps: ${{ steps.filter.outputs.apps }}
    steps:
      - name: Set filters variable test
        id: set_filters
        run: |
          FILTERS="exampleapp: apps/exampleapp/**\ndashboard: apps/dashboard/**"
          echo "::set-output name=filters::$FILTERS"
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          list-files: shell
          filters: |
            exampleapp: "apps/exampleapp/**"
            dashboard: "apps/dashboard/**"
      - name: Show outputs
        run: |
          echo "===================="
          echo ${{ steps.filter.outputs.exampleapp}}
          echo ${{ steps.filter.outputs.dashboard}}
          echo ${{ steps.set_filters.outputs.filters}}
          echo "===================="

  # apps:
  #   needs: changes
  #   if: ${{ needs.changes.outputs.apps == 'true' }}
  #   runs-on: [ubuntu-latest]
  #   steps:
  #     - run: echo ${{ needs.changes.outputs.apps }}

  # run_test:
  #   needs: collect_info
  #   runs-on: [ubuntu-latest]
  #   strategy:
  #     matrix:
  #       apps: ${{fromJson(needs.collect_info.outputs.apps)}}
  #   steps:
  #     - run: echo ${{ matrix.apps }}
